name: Cron
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  cron:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - run: curl https://spotify-widget.calebden.io/api/cron?token=${{ secrets.CRON_TOKEN }}